import { CAREER_THEMES } from './themes'
import { CAREER_WORK } from './workStyles'
import type { Career } from './types'

const BASE_CAREERS: Omit<Career, 'themes' | 'workStyleTags'>[] = [
  {
    id: 'ai-specialist',
    field: 'tech',
    interests: ['technology', 'data', 'problemSolving'],
    strengths: ['analyticalThinking', 'curiosity', 'practicalThinking'],
    skillTags: ['digital', 'analyticalThinking', 'systems'],
    related: ['software-developer', 'data-scientist', 'human-factors-specialist'],
  },
  {
    id: 'software-developer',
    field: 'tech',
    interests: ['technology', 'engineering', 'product'],
    strengths: ['problemSolving', 'practicalThinking', 'initiative'],
    skillTags: ['digital', 'problemSolving', 'systems'],
    related: ['ai-specialist', 'ux-ui-designer', 'electrical-engineer'],
  },
  {
    id: 'data-scientist',
    field: 'tech',
    interests: ['data', 'technology', 'science'],
    strengths: ['analyticalThinking', 'curiosity', 'problemSolving'],
    skillTags: ['analyticalThinking', 'numbers', 'research'],
    related: ['ai-specialist', 'economist', 'research-scientist'],
  },
  {
    id: 'cybersecurity-specialist',
    field: 'tech',
    interests: ['technology', 'problemSolving', 'data'],
    strengths: ['analyticalThinking', 'practicalThinking', 'curiosity'],
    skillTags: ['digital', 'analyticalThinking', 'systems'],
    related: ['software-developer', 'policy-analyst', 'electrical-engineer'],
  },
  {
    id: 'business-manager',
    field: 'business',
    interests: ['business', 'leadership', 'people'],
    strengths: ['leadership', 'organization', 'communication'],
    skillTags: ['leadership', 'planning', 'communication'],
    related: ['operations-manager', 'management-consultant', 'entrepreneur'],
  },
  {
    id: 'entrepreneur',
    field: 'business',
    interests: ['business', 'product', 'leadership'],
    strengths: ['initiative', 'leadership', 'adaptability'],
    skillTags: ['leadership', 'planning', 'creativity'],
    related: ['business-manager', 'marketing-specialist', 'content-strategist'],
  },
  {
    id: 'management-consultant',
    field: 'business',
    interests: ['business', 'problemSolving', 'people'],
    strengths: ['analyticalThinking', 'communication', 'organization'],
    skillTags: ['analyticalThinking', 'communication', 'planning'],
    related: ['operations-manager', 'policy-analyst', 'economist'],
  },
  {
    id: 'operations-manager',
    field: 'business',
    interests: ['business', 'leadership', 'product'],
    strengths: ['organization', 'practicalThinking', 'leadership'],
    skillTags: ['planning', 'systems', 'leadership'],
    related: ['business-manager', 'management-consultant', 'sustainability-specialist'],
  },
  {
    id: 'physicist',
    field: 'science',
    interests: ['science', 'problemSolving', 'data'],
    strengths: ['analyticalThinking', 'curiosity', 'problemSolving'],
    skillTags: ['research', 'analyticalThinking', 'numbers'],
    related: ['astrophysicist', 'research-scientist', 'electrical-engineer'],
  },
  {
    id: 'chemist',
    field: 'science',
    interests: ['science', 'engineering', 'problemSolving'],
    strengths: ['curiosity', 'practicalThinking', 'analyticalThinking'],
    skillTags: ['labwork', 'research', 'analyticalThinking'],
    related: ['research-scientist', 'food-scientist', 'biotechnologist'],
  },
  {
    id: 'research-scientist',
    field: 'science',
    interests: ['science', 'data', 'education'],
    strengths: ['curiosity', 'analyticalThinking', 'organization'],
    skillTags: ['research', 'writing', 'labwork'],
    related: ['physicist', 'medical-researcher', 'educational-researcher'],
  },
  {
    id: 'biologist',
    field: 'biology',
    interests: ['science', 'biology', 'nature'],
    strengths: ['curiosity', 'analyticalThinking', 'practicalThinking'],
    skillTags: ['research', 'observation', 'fieldwork'],
    related: ['geneticist', 'wildlife-biologist', 'environmental-scientist'],
  },
  {
    id: 'biotechnologist',
    field: 'biology',
    interests: ['science', 'biology', 'health'],
    strengths: ['practicalThinking', 'curiosity', 'problemSolving'],
    skillTags: ['labwork', 'research', 'systems'],
    related: ['geneticist', 'chemist', 'biomedical-engineer'],
  },
  {
    id: 'geneticist',
    field: 'biology',
    interests: ['science', 'biology', 'data'],
    strengths: ['analyticalThinking', 'curiosity', 'organization'],
    skillTags: ['labwork', 'research', 'analyticalThinking'],
    related: ['biologist', 'medical-researcher', 'biotechnologist'],
  },
  {
    id: 'doctor',
    field: 'health',
    interests: ['health', 'people', 'biology'],
    strengths: ['empathy', 'practicalThinking', 'communication'],
    skillTags: ['care', 'empathy', 'problemSolving'],
    related: ['pharmacist', 'public-health-specialist', 'medical-researcher'],
  },
  {
    id: 'pharmacist',
    field: 'health',
    interests: ['health', 'biology', 'science'],
    strengths: ['organization', 'analyticalThinking', 'empathy'],
    skillTags: ['care', 'analyticalThinking', 'communication'],
    related: ['doctor', 'chemist', 'public-health-specialist'],
  },
  {
    id: 'medical-researcher',
    field: 'health',
    interests: ['health', 'science', 'data'],
    strengths: ['curiosity', 'analyticalThinking', 'organization'],
    skillTags: ['research', 'labwork', 'writing'],
    related: ['geneticist', 'research-scientist', 'doctor'],
  },
  {
    id: 'public-health-specialist',
    field: 'health',
    interests: ['health', 'society', 'people'],
    strengths: ['empathy', 'organization', 'communication'],
    skillTags: ['policy', 'communication', 'planning'],
    related: ['policy-analyst', 'doctor', 'teacher'],
  },
  {
    id: 'geologist',
    field: 'environment',
    interests: ['nature', 'science', 'engineering'],
    strengths: ['curiosity', 'practicalThinking', 'analyticalThinking'],
    skillTags: ['fieldwork', 'observation', 'research'],
    related: ['environmental-scientist', 'civil-engineer', 'sustainability-specialist'],
  },
  {
    id: 'environmental-scientist',
    field: 'environment',
    interests: ['nature', 'science', 'society'],
    strengths: ['curiosity', 'analyticalThinking', 'empathy'],
    skillTags: ['research', 'fieldwork', 'policy'],
    related: ['sustainability-specialist', 'geologist', 'wildlife-biologist'],
  },
  {
    id: 'sustainability-specialist',
    field: 'environment',
    interests: ['nature', 'business', 'society'],
    strengths: ['organization', 'communication', 'practicalThinking'],
    skillTags: ['planning', 'policy', 'systems'],
    related: ['environmental-scientist', 'urban-planner', 'operations-manager'],
  },
  {
    id: 'mechanical-engineer',
    field: 'engineering',
    interests: ['engineering', 'product', 'problemSolving'],
    strengths: ['practicalThinking', 'problemSolving', 'initiative'],
    skillTags: ['systems', 'problemSolving', 'planning'],
    related: ['electrical-engineer', 'aerospace-engineer', 'biomedical-engineer'],
  },
  {
    id: 'civil-engineer',
    field: 'engineering',
    interests: ['engineering', 'society', 'product'],
    strengths: ['practicalThinking', 'organization', 'problemSolving'],
    skillTags: ['planning', 'systems', 'fieldwork'],
    related: ['architect', 'urban-planner', 'mechanical-engineer'],
  },
  {
    id: 'electrical-engineer',
    field: 'engineering',
    interests: ['engineering', 'technology', 'problemSolving'],
    strengths: ['analyticalThinking', 'practicalThinking', 'problemSolving'],
    skillTags: ['systems', 'digital', 'problemSolving'],
    related: ['software-developer', 'aerospace-engineer', 'mechanical-engineer'],
  },
  {
    id: 'biomedical-engineer',
    field: 'engineering',
    interests: ['engineering', 'health', 'technology'],
    strengths: ['practicalThinking', 'curiosity', 'empathy'],
    skillTags: ['systems', 'labwork', 'problemSolving'],
    related: ['doctor', 'biotechnologist', 'mechanical-engineer'],
  },
  {
    id: 'psychologist',
    field: 'psychology',
    interests: ['psychology', 'people', 'health'],
    strengths: ['empathy', 'communication', 'curiosity'],
    skillTags: ['empathy', 'research', 'communication'],
    related: ['behavioral-researcher', 'teacher', 'human-factors-specialist'],
  },
  {
    id: 'behavioral-researcher',
    field: 'psychology',
    interests: ['psychology', 'data', 'science'],
    strengths: ['curiosity', 'analyticalThinking', 'organization'],
    skillTags: ['research', 'analyticalThinking', 'writing'],
    related: ['psychologist', 'data-scientist', 'educational-researcher'],
  },
  {
    id: 'human-factors-specialist',
    field: 'psychology',
    interests: ['people', 'product', 'technology'],
    strengths: ['empathy', 'analyticalThinking', 'practicalThinking'],
    skillTags: ['observation', 'design', 'research'],
    related: ['ux-ui-designer', 'psychologist', 'ai-specialist'],
  },
  {
    id: 'graphic-designer',
    field: 'creative',
    interests: ['creativity', 'media', 'product'],
    strengths: ['creativity', 'initiative', 'communication'],
    skillTags: ['design', 'creativity', 'digital'],
    related: ['art-director', 'ux-ui-designer', 'content-strategist'],
  },
  {
    id: 'ux-ui-designer',
    field: 'creative',
    interests: ['creativity', 'technology', 'people'],
    strengths: ['empathy', 'creativity', 'practicalThinking'],
    skillTags: ['design', 'observation', 'digital'],
    related: ['human-factors-specialist', 'graphic-designer', 'software-developer'],
  },
  {
    id: 'animator',
    field: 'creative',
    interests: ['creativity', 'media', 'education'],
    strengths: ['creativity', 'initiative', 'organization'],
    skillTags: ['design', 'creativity', 'digital'],
    related: ['art-director', 'graphic-designer', 'content-strategist'],
  },
  {
    id: 'art-director',
    field: 'creative',
    interests: ['creativity', 'media', 'leadership'],
    strengths: ['creativity', 'leadership', 'communication'],
    skillTags: ['design', 'leadership', 'communication'],
    related: ['graphic-designer', 'marketing-specialist', 'animator'],
  },
  {
    id: 'marketing-specialist',
    field: 'media',
    interests: ['media', 'business', 'people'],
    strengths: ['communication', 'creativity', 'initiative'],
    skillTags: ['communication', 'writing', 'planning'],
    related: ['content-strategist', 'communications-specialist', 'entrepreneur'],
  },
  {
    id: 'journalist',
    field: 'media',
    interests: ['media', 'society', 'people'],
    strengths: ['curiosity', 'communication', 'initiative'],
    skillTags: ['writing', 'research', 'communication'],
    related: ['communications-specialist', 'policy-analyst', 'content-strategist'],
  },
  {
    id: 'content-strategist',
    field: 'media',
    interests: ['media', 'creativity', 'education'],
    strengths: ['communication', 'organization', 'creativity'],
    skillTags: ['writing', 'planning', 'communication'],
    related: ['marketing-specialist', 'instructional-designer', 'journalist'],
  },
  {
    id: 'communications-specialist',
    field: 'media',
    interests: ['media', 'people', 'society'],
    strengths: ['communication', 'empathy', 'organization'],
    skillTags: ['communication', 'writing', 'collaboration'],
    related: ['journalist', 'public-administration-specialist', 'marketing-specialist'],
  },
  {
    id: 'economist',
    field: 'finance',
    interests: ['finance', 'society', 'business'],
    strengths: ['analyticalThinking', 'curiosity', 'communication'],
    skillTags: ['numbers', 'research', 'analyticalThinking'],
    related: ['financial-analyst', 'policy-analyst', 'data-scientist'],
  },
  {
    id: 'financial-analyst',
    field: 'finance',
    interests: ['finance', 'business', 'data'],
    strengths: ['analyticalThinking', 'organization', 'practicalThinking'],
    skillTags: ['numbers', 'analyticalThinking', 'planning'],
    related: ['economist', 'financial-planner', 'management-consultant'],
  },
  {
    id: 'financial-planner',
    field: 'finance',
    interests: ['people', 'finance', 'business'],
    strengths: ['empathy', 'organization', 'communication'],
    skillTags: ['numbers', 'communication', 'planning'],
    related: ['financial-analyst', 'business-manager', 'lawyer'],
  },
  {
    id: 'lawyer',
    field: 'law',
    interests: ['society', 'people', 'problemSolving'],
    strengths: ['analyticalThinking', 'communication', 'organization'],
    skillTags: ['writing', 'policy', 'communication'],
    related: ['policy-analyst', 'public-administration-specialist', 'journalist'],
  },
  {
    id: 'policy-analyst',
    field: 'law',
    interests: ['society', 'data', 'education'],
    strengths: ['analyticalThinking', 'curiosity', 'communication'],
    skillTags: ['policy', 'research', 'writing'],
    related: ['economist', 'public-health-specialist', 'lawyer'],
  },
  {
    id: 'public-administration-specialist',
    field: 'law',
    interests: ['society', 'leadership', 'people'],
    strengths: ['organization', 'leadership', 'empathy'],
    skillTags: ['planning', 'policy', 'collaboration'],
    related: ['policy-analyst', 'operations-manager', 'communications-specialist'],
  },
  {
    id: 'teacher',
    field: 'education',
    interests: ['education', 'people', 'society'],
    strengths: ['empathy', 'communication', 'organization'],
    skillTags: ['teaching', 'communication', 'empathy'],
    related: ['instructional-designer', 'educational-researcher', 'psychologist'],
  },
  {
    id: 'instructional-designer',
    field: 'education',
    interests: ['education', 'creativity', 'technology'],
    strengths: ['organization', 'creativity', 'empathy'],
    skillTags: ['teaching', 'design', 'planning'],
    related: ['teacher', 'content-strategist', 'ux-ui-designer'],
  },
  {
    id: 'educational-researcher',
    field: 'education',
    interests: ['education', 'data', 'society'],
    strengths: ['curiosity', 'analyticalThinking', 'organization'],
    skillTags: ['research', 'analyticalThinking', 'writing'],
    related: ['teacher', 'behavioral-researcher', 'research-scientist'],
  },
  {
    id: 'architect',
    field: 'architecture',
    interests: ['creativity', 'engineering', 'product'],
    strengths: ['creativity', 'practicalThinking', 'organization'],
    skillTags: ['design', 'planning', 'systems'],
    related: ['urban-planner', 'landscape-architect', 'civil-engineer'],
  },
  {
    id: 'urban-planner',
    field: 'architecture',
    interests: ['society', 'engineering', 'nature'],
    strengths: ['organization', 'analyticalThinking', 'communication'],
    skillTags: ['planning', 'policy', 'systems'],
    related: ['architect', 'civil-engineer', 'sustainability-specialist'],
  },
  {
    id: 'landscape-architect',
    field: 'architecture',
    interests: ['nature', 'creativity', 'engineering'],
    strengths: ['creativity', 'practicalThinking', 'empathy'],
    skillTags: ['design', 'fieldwork', 'planning'],
    related: ['architect', 'environmental-scientist', 'urban-planner'],
  },
  {
    id: 'agricultural-scientist',
    field: 'agriculture',
    interests: ['nature', 'science', 'engineering'],
    strengths: ['practicalThinking', 'curiosity', 'problemSolving'],
    skillTags: ['research', 'fieldwork', 'labwork'],
    related: ['food-scientist', 'forestry-specialist', 'environmental-scientist'],
  },
  {
    id: 'food-scientist',
    field: 'agriculture',
    interests: ['science', 'health', 'product'],
    strengths: ['practicalThinking', 'analyticalThinking', 'curiosity'],
    skillTags: ['labwork', 'research', 'systems'],
    related: ['chemist', 'agricultural-scientist', 'public-health-specialist'],
  },
  {
    id: 'forestry-specialist',
    field: 'agriculture',
    interests: ['nature', 'science', 'society'],
    strengths: ['practicalThinking', 'organization', 'curiosity'],
    skillTags: ['fieldwork', 'observation', 'planning'],
    related: ['wildlife-biologist', 'environmental-scientist', 'agricultural-scientist'],
  },
  {
    id: 'aerospace-engineer',
    field: 'space',
    interests: ['engineering', 'space', 'technology'],
    strengths: ['practicalThinking', 'problemSolving', 'analyticalThinking'],
    skillTags: ['systems', 'problemSolving', 'planning'],
    related: ['mechanical-engineer', 'astrophysicist', 'electrical-engineer'],
  },
  {
    id: 'astrophysicist',
    field: 'space',
    interests: ['science', 'space', 'data'],
    strengths: ['curiosity', 'analyticalThinking', 'problemSolving'],
    skillTags: ['research', 'numbers', 'analyticalThinking'],
    related: ['physicist', 'aerospace-engineer', 'research-scientist'],
  },
  {
    id: 'veterinarian',
    field: 'animals',
    interests: ['animals', 'health', 'people'],
    strengths: ['empathy', 'practicalThinking', 'communication'],
    skillTags: ['care', 'problemSolving', 'empathy'],
    related: ['animal-scientist', 'wildlife-biologist', 'doctor'],
  },
  {
    id: 'animal-scientist',
    field: 'animals',
    interests: ['animals', 'science', 'nature'],
    strengths: ['curiosity', 'practicalThinking', 'analyticalThinking'],
    skillTags: ['research', 'labwork', 'observation'],
    related: ['veterinarian', 'agricultural-scientist', 'biologist'],
  },
  {
    id: 'wildlife-biologist',
    field: 'animals',
    interests: ['animals', 'nature', 'science'],
    strengths: ['curiosity', 'practicalThinking', 'empathy'],
    skillTags: ['fieldwork', 'observation', 'research'],
    related: ['biologist', 'environmental-scientist', 'forestry-specialist'],
  },
]

export const CAREERS: Career[] = BASE_CAREERS.map((career) => ({
  ...career,
  themes: CAREER_THEMES[career.id] ?? [],
  workStyleTags: CAREER_WORK[career.id] ?? ['collaborative'],
}))

export const CAREER_BY_ID: Record<string, Career> = Object.fromEntries(
  CAREERS.map((career) => [career.id, career]),
)

export function getCareer(id: string) {
  return CAREER_BY_ID[id] ?? null
}
